"""empty message

Revision ID: f91fdc22e9ab
Revises: 07573dd37413
Create Date: 2024-03-02 20:01:45.248641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91fdc22e9ab'
down_revision = '07573dd37413'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
